version: "3"

volumes:
  mongo_data: {}

services:
  faust:
    build:
      context: .
      dockerfile: ./dockerfiles/faust/Dockerfile
    volumes:
      - ./services:/services
    ports:
      - "6066:6066"
    env_file:
      - ./.envs/.env_vars
    command: sh /faust_run.sh
    restart: unless-stopped

  mongodb:
    image: mongo:4.0.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongo_data:/var/lib/mongodb/data/
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:5.2.0
    restart: unless-stopped
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    expose:
      - "2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
